library(shiny)
library(shinyjs)
library(ff)
library(plotly)
library(tseries)
library(lubridate)
library(plyr)
library(dplyr)
library(forecast)
library(DT)
library(shinydashboard)
#library(highcharter)
#library(rsconnect)
#library(multidplyr)
#library(ddR)
#library(httr)
#set_config(use_proxy(url = "internetproxy.devops.vodafone.com", port = 3128))
#devtools::install_github("rstudio/shiny")
#options(RCurlOptions = list(proxy = "internetproxy.devops.vodafone.com:3128"))
#deployApp()

